### ISSUE TITLE
Bulk Insert/update Incorrect Data Type

### ISSUE THREAD

**Issue by Jeff-14159** [TimelordUK/node-sqlserver-v8#151] opened 2020-04-03 18:43 UTC
Using the bulk insert/update the data type may be incorrect, I was using a large number such as "2829365649" inserting into a column that is a Numeric(18,0) the value becomes "-1465601647" and I believe it changed because it was using the wrong data type.

Note: is using a regular insert query it works ok it is only when it is passed into the bulk insert

as a work around I'm checking and doing .toString() on large whole numbers and that seems to be working for now...

Thanks,
Jeff

0.8.9

**Comment by TimelordUK** [comment] 2020-04-04 17:19
I am sure you are seeing this however with a test I cannot reproduce it -i.e. i create table as below and use bulk table insert on rows using large unsigned into numeric 18,0 as suggested.

```sql
USE [scratch]
GO

/****** Object:  Table [dbo].[bulkColumn]    Script Date: 04/04/2020 18:15:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[bulkColumn](
	[pkid] [int] NOT NULL,
	[col1] [numeric](18, 0) NULL,
PRIMARY KEY CLUSTERED 
(
	[pkid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
```
```javascript
  function hugeUnsignedTest (batchSize, selectAfterInsert, runUpdateFunction, testDone) {
    const params = {
      columnType: 'Numeric(18,0)',
      buildFunction: i => 2829365649 + i * 2,
      updateFunction: runUpdateFunction ? i => i * 3 : null,
      check: selectAfterInsert,
      deleteAfterTest: false,
      batchSize: batchSize
    }

    simpleColumnBulkTest(params, () => {
      testDone()
    })
  }

  test(`bulk insert/select int column of huge unsigned batchSize ${test1BatchSize}`, testDone => {
    hugeUnsignedTest(test1BatchSize, true, false, () => {
      testDone()
    })
  })
```

select * from [dbo].[bulkColumn]
0	2829365649
1	2829365651
2	2829365653
3	2829365655
4	2829365657
5	2829365659
6	2829365661
7	2829365663
8	2829365665
9	2829365667

**Comment by Jeff-14159** [comment] 2020-04-06 18:50
thanks for the quick response and test case you used, it would appear the if all rows have a big value things work, but when a mix is applied things break.

so:
[ { id: 0, prop: 2829365649 }, { id: 1,  prop: 2829365649 },  { id: 2,  prop: 2829365649 } ]   -- works ok
[ { id: 0,  prop: 2829365649 }, { id: 1,  prop: 2829365649 }, { id: 2, prop: 0 } ]  -- don't work
[ { id: 0,  prop: 2829365649 }, { id: 1, prop: 0 }, {id: 2,  prop: 2829365649 } ] -- don't work

Thanks,
Jeff

**Comment by TimelordUK** [comment] 2020-04-10 17:04
thanks you are quite correct - when presented with a mix of int32 and int64 the vector is sent as int 32 thus we see the issue you describe.

its fixed in latest version

**Closed** 2020-04-10 17:55 UTC
