### ISSUE TITLE
Connect Segmentation fault on debian:9 ( docker image node:14 ) 

### ISSUE THREAD

**Issue by zmooky** [TimelordUK/node-sqlserver-v8#223] opened 2021-10-31 15:38 UTC
Connection to mssql fails with segmentation fault on debian 9. 

```
libodbc1:amd64 (2.3.7)
odbcinst (2.3.7)
odbcinst1debian2:amd64 (2.3.7)
unixodbc (2.3.7)
unixodbc-dev (2.3.7)
msodbcsql17 (17.8.1.1-1)
```

This example works on wsl2 ubuntu 20.04, 18.04, etc. 
```
const sql = require("msnodesqlv8");
const query = "SELECT name FROM sys.databases";

const connectionString = "Server=mssql;Database=master;Uid=sa;Pwd=YourPasswordHere;Driver=ODBC Driver 17 for SQL Server";

sql.query(connectionString, query, (err, rows) => {
    if (err) {
        console.log(err);
        return;
    }
    console.log(rows);
});
```

Reproduce on debian:9 clean installation ( docker image ): 
```
curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list

apt update
apt install -y build-essential
apt install -y unixodbc-dev
ACCEPT_EULA=Y apt install -y msodbcsql17

mkdir test
cd test/

npm init -y
npm i -g node-gyp
npm i msnodesqlv8
```
Segmentation crash trace:

```
PID 946 received SIGSEGV for address: 0x2c
/test/node_modules/segfault-handler/build/Release/segfault-handler.node(+0x2cc1)[0x7f7eb65facc1]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x110e0)[0x7f7ebd3e30e0]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x14)[0x7f7ebd0ae524]
node[0x151148e]
/usr/lib/x86_64-linux-gnu/libssl.so.1.1(SSL_new+0x43a)[0x7f7ea5bbdb9a]
/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1(+0x173c38)[0x7f7ea7d54c38]
/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1(+0x16e2c2)[0x7f7ea7d4f2c2]
/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1(+0x16eb59)[0x7f7ea7d4fb59]
/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1(+0x13667f)[0x7f7ea7d1767f]
/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1(+0x133f4d)[0x7f7ea7d14f4d]
/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1(+0x134c32)[0x7f7ea7d15c32]
/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1(+0x9859e)[0x7f7ea7c7959e]
/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1(+0xd273e)[0x7f7ea7cb373e]
/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1(SQLDriverConnectW+0x13ad)[0x7f7ea7c78a4d]
/usr/lib/x86_64-linux-gnu/libodbc.so.2(SQLDriverConnectW+0x243)[0x7f7eb63b3a03]
/test/node_modules/msnodesqlv8/build/Release/sqlserverv8.node(_ZN5mssql14OdbcConnection8try_openERKNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEEi+0x59d)[0x7f7ebe27821d]
/test/node_modules/msnodesqlv8/build/Release/sqlserverv8.node(_ZN5mssql13OdbcOperation7ExecuteEv+0x2e)[0x7f7ebe27cd1e]
node[0x13b9224]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x74a4)[0x7f7ebd3d94a4]
```

**Comment by TimelordUK** [comment] 2021-10-31 18:50
this is almost certainly related to the libssl you have installed

if you have access to openbrew 

brew install openssl
cd /usr/lib
sudo mv /lib/x86_64-linux-gnu/libssl.so.1.1 /lib/x86_64-linux-gnu/libssl.so.1.1.old
sudo ln -s /home/linuxbrew/.linuxbrew/opt/openssl@3/lib/libssl.so  libssl.so.1.1
lrwxrwxrwx   1 root root      54 Oct 31 18:41 libssl.so.1.1 -> /home/linuxbrew/.linuxbrew/opt/openssl@3/lib/libssl.so

```cmd
~/dev/js/published/samples/javascript$ node throttle.js 
stream fetch query with throttle back to server to slow results
on.submitted select top 750 * from master..syscolumns;
18:45:43 - [0] (rowCount 100): pause and dispatch 100 rows ...
18:45:43 - [0] (rowCount 100): ... done, resume query
18:45:44 - [1] (rowCount 200): pause and dispatch 100 rows ...
18:45:44 - [1] (rowCount 200): ... done, resume query
18:45:46 - [2] (rowCount 300): pause and dispatch 100 rows ...
18:45:46 - [2] (rowCount 300): ... done, resume query
18:45:47 - [3] (rowCount 400): pause and dispatch 100 rows ...
18:45:47 - [3] (rowCount 400): ... done, resume query
18:45:49 - [4] (rowCount 500): pause and dispatch 100 rows ...
18:45:49 - [4] (rowCount 500): ... done, resume query
18:45:50 - [5] (rowCount 600): pause and dispatch 100 rows ...
18:45:50 - [5] (rowCount 600): ... done, resume query
18:45:52 - [6] (rowCount 700): pause and dispatch 100 rows ...
18:45:52 - [6] (rowCount 700): ... done, resume query
on.done
[7] (rowCount 750): last dispatch 50 rows
done
-pc:~/dev/js/published/samples/javascript$ uname -a
Linux -pc 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux
```

```cmd

the MS odbc driver will dynamically try and load libssl and it is probably installed in same folder as libs below.  However on debian i find this version does not appear to work.

dev/js/published/samples/javascript$  ldd /opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1 
	linux-vdso.so.1 (0x00007ffd7b597000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f82e02fa000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f82e02f0000)
	libodbcinst.so.2 => /lib/x86_64-linux-gnu/libodbcinst.so.2 (0x00007f82e00d5000)
	libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f82dfff5000)
	libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f82dffa8000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f82dfe24000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f82dfc9f000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f82dfc85000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f82dfc64000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f82dfaa3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f82e0739000)
	libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f82dfa6f000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f82dfa69000)
	libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f82dfa58000)
	libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f82dfa51000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f82dfa37000)

```

**Comment by TimelordUK** [comment] 2021-11-07 16:02
a slightly better approach that works on my Debian installation is to make use of the LD_PRELOAD variable

```bash
me@me-pc:~/dev/js/published/samples/javascript$ export LD_PRELOAD=/usr/lib/libssl.so
me@me-pc:~/dev/js/published/samples/javascript$ ps -ef | grep node
me   6350  1576 54 15:57 pts/0    00:00:39 node pooling.js
me   6634  6370  0 15:58 pts/1    00:00:00 grep node
me@me-pc:~/dev/js/published/samples/javascript$ pldd 6350
6350:	/home/me/.nvm/versions/node/v16.13.0/bin/node
linux-vdso.so.1
/usr/lib/libssl.so.1.1
/lib/x86_64-linux-gnu/libdl.so.2
/lib/x86_64-linux-gnu/libstdc++.so.6
/lib/x86_64-linux-gnu/libm.so.6
/lib/x86_64-linux-gnu/libgcc_s.so.1
/lib/x86_64-linux-gnu/libpthread.so.0
/lib/x86_64-linux-gnu/libc.so.6
/lib64/ld-linux-x86-64.so.2
/home/linuxbrew/.linuxbrew/Cellar/openssl@1.1/1.1.1l_1/lib/libcrypto.so.1.1
/home/me/dev/js/published/node_modules/msnodesqlv8/build/Release/sqlserverv8.node
/lib/x86_64-linux-gnu/libodbc.so.2
/usr/lib/x86_64-linux-gnu/gconv/UTF-16.so
/opt/microsoft/msodbcsql17/lib64/libmsodbcsql-17.8.so.1.1
/lib/x86_64-linux-gnu/librt.so.1
/lib/x86_64-linux-gnu/libodbcinst.so.2
/lib/x86_64-linux-gnu/libkrb5.so.3
/lib/x86_64-linux-gnu/libgssapi_krb5.so.2
/lib/x86_64-linux-gnu/libk5crypto.so.3
/lib/x86_64-linux-gnu/libcom_err.so.2
/lib/x86_64-linux-gnu/libkrb5support.so.0
/lib/x86_64-linux-gnu/libkeyutils.so.1
/lib/x86_64-linux-gnu/libresolv.so.2
/lib/x86_64-linux-gnu/libnss_files.so.2
me@me-pc:~/dev/js/published/samples/javascript$ 
```

**Comment by TimelordUK** [comment] 2022-07-07 21:45
glad you got it working - just to  make a note here another option is to use LD_PRELOAD

```sh
cd node_modules/msnodesqlv8/build/Release
ln -s /home/linuxbrew/.linuxbrew/opt/openssl@3/lib/libssl.so.3 libssl.so.1.1
# libssl.so.1.1 -> /home/linuxbrew/.linuxbrew/opt/openssl@3/lib/libssl.so.3
cd ../..
export LD_PRELOAD=~/dev/js/v8/node_modules/msnodesqlv8/build/Release/libssl.so.1.1

node samples/javascript/throttle.js
stream fetch query with throttle back to server to slow results
on.submitted select top 750 * from master..syscolumns;
10:45:01 PM - [0] (rowCount 100): pause and dispatch 100 rows ...
10:45:01 PM - [0] (rowCount 100): ... done, resume query
10:45:02 PM - [1] (rowCount 200): pause and dispatch 100 rows ...

```

**Comment by lroal** [comment] 2022-07-25 10:39
I am getting segmentation fault on on debian11 (docker image 16-bullseye) as well.
The only error I see is:
"Segmentation fault"

**Code:**
```
const sql = require("msnodesqlv8");
const query = "SELECT name FROM sys.databases";

const connectionString = "server=db;Database=rems;User Id=sa;Password=P@ssword123;Driver={ODBC Driver 18 for SQL Server}";
sql.query(connectionString, query, (err, rows) => {
    if (err) {
        console.log('err')
        console.log(err);
        return;
    }
    console.log(rows);
});
```

**Docker script**
```
ARG VARIANT=16-bullseye
FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:0-${VARIANT}
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN echo msodbcsql18 msodbcsql/ACCEPT_EULA boolean true | sudo debconf-set-selections | apt-get install -y msodbcsql18
RUN apt-get install -y unixodbc-dev
```

**Comment by TimelordUK** [comment] 2022-07-25 10:48
I’m not sure if I have replied in this thread I’m away from desktop. This is almost guaranteed I’m afraid to be related to ssl. The only reliable way I found to fix it is to install brew OpenSSL and set system up such that this version is loaded for example from ld preload. This error is being raised by the ms library opening
A connection to OpenSSL which itself core dumps due to I assume incompatible version

**Comment by TimelordUK** [comment] 2022-07-25 20:28
for example if I install and run on WLS Ubuntu I get stack trace below

```txt
Thread 8 "node" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff4c2d700 (LWP 380)]
0x00000000019b041b in OPENSSL_sk_free ()
(gdb) bt
#0  0x00000000019b041b in OPENSSL_sk_free ()
#1  0x000000000194c000 in CRYPTO_free_ex_data ()
#2  0x0000000001855d5a in BIO_free_all ()
#3  0x00007ffd5e40c442 in SSL_free () from /lib/x86_64-linux-gnu/libssl.so.1.1
#4  0x00007ffff4185138 in ?? () from /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.0.so.1.1
#5  0x00007ffff417f23b in ?? () from /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.0.so.1.1
#6  0x00007ffff417f640 in ?? () from /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.0.so.1.1
#7  0x00007ffff41492cf in ?? () from /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.0.so.1.1
#8  0x00007ffff41465cd in ?? () from /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.0.so.1.1
#9  0x00007ffff414737b in ?? () from /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.0.so.1.1
#10 0x00007ffff41479d4 in ?? () from /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.0.so.1.1
#11 0x00007ffff40b52ee in ?? () from /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.0.so.1.1
#12 0x00007ffff40e9dee in ?? () from /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.0.so.1.1
#13 0x00007ffff40b460a in SQLDriverConnectW () from /opt/microsoft/msodbcsql18/lib64/libmsodbcsql-18.0.so.1.1
```

then I set LD as below

```sh
me@DESKTOP:~/dev/js/v8/node_modules/msnodesqlv8$ pwd
/home/me/dev/js/v8/node_modules/msnodesqlv8
me@DESKTOP:~/dev/js/v8/node_modules/msnodesqlv8$ export LD_PRELOAD=/home/me/libssl.so.1.1
me@DESKTOP:~/dev/js/v8/node_modules/msnodesqlv8$ ls -l /home/me/libssl.so.1.1
lrwxrwxrwx 1 me me 56 Jul  8 23:34 /home/me/libssl.so.1.1 -> /home/linuxbrew/.linuxbrew/opt/openssl@3/lib/libssl.so.3
me@DESKTOP:~/dev/js/v8/node_modules/msnodesqlv8$
```

then i run

```txt
me@DESKTOP:~/dev/js/v8/node_modules/msnodesqlv8$ npm run test test/connect

> msnodesqlv8@2.6.0 test
> nyc --reporter=html --reporter=text mocha --reporter mochawesome --require mochawesome/register



  connection
    ✔ connection closes OK in sequence with query (174ms)
    ✔ verify closed connection throws an exception (160ms)
    ✔ verify connection is not closed prematurely until a query is complete (237ms)
    ✔ verify that close immediately flag only accepts booleans (175ms)
```

**Comment by TimelordUK** [comment] 2022-07-25 20:59
note ldd on ms lib now picks up our patched libssl

I have not tried but installing open sll3 directly if you have no linux package may also work e.g. [install ssl](https://nextgentips.com/2022/03/23/how-to-install-openssl-3-on-ubuntu-20-04/)

```txt
me@DESKTOP:~/dev/js/v8/node_modules/msnodesqlv8$ ldd /usr/lib/libmsodbcsql-18.so
        linux-vdso.so.1 (0x00007fff587ff000)
        /home/me/libssl.so.1.1 (0x00007f65c6929000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f65c691a000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f65c6910000)
        libodbcinst.so.2 => /lib/x86_64-linux-gnu/libodbcinst.so.2 (0x00007f65c66f5000)
        libkrb5.so.3 => /lib/x86_64-linux-gnu/libkrb5.so.3 (0x00007f65c6618000)
        libgssapi_krb5.so.2 => /lib/x86_64-linux-gnu/libgssapi_krb5.so.2 (0x00007f65c65cb000)
        libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f65c63e7000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f65c6298000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f65c627d000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f65c625a000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f65c6068000)
        libcrypto.so.3 => /home/linuxbrew/.linuxbrew/Cellar/openssl@3/3.0.5/lib/libcrypto.so.3 (0x00007f65c5a10000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f65c6fe4000)
        libk5crypto.so.3 => /lib/x86_64-linux-gnu/libk5crypto.so.3 (0x00007f65c59df000)
        libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f65c59d8000)
        libkrb5support.so.0 => /lib/x86_64-linux-gnu/libkrb5support.so.0 (0x00007f65c59c9000)
        libkeyutils.so.1 => /lib/x86_64-linux-gnu/libkeyutils.so.1 (0x00007f65c59c2000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f65c59a6000)
me@DESKTOP:~/dev/js/v8/node_modules/msnodesqlv8$
```

**Comment by lroal** [comment] 2022-07-26 10:02
I do not understand how to replace builtin ssl with ssl 3. And it needs to be done inside the docker config. I can't find a reliable way to automate the steps

**Comment by TimelordUK** [comment] 2022-07-26 10:43
Can you build say 1.0.2 as per below

I am afraid I cannot help further at this time the issue is somehow related to a compatibility issue. 

Just as a test have you tried a connection unencrypted 

Encrypt=False in connect string does this bypass tls. 


FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y build-essential cmake zlib1g-dev libcppunit-dev git subversion wget && rm -rf /var/lib/apt/lists/*

RUN wget https://www.openssl.org/source/openssl-1.0.2g.tar.gz -O - | tar -xz
WORKDIR /openssl-1.0.2g
RUN ./config --prefix=/usr/local/openssl --openssldir=/usr/local/openssl && make && make install

**Comment by lroal** [comment] 2022-07-26 10:59
I went for alpine linux image instead of debian. And it works now. Thanks for your help.

**Comment by lroal** [comment] 2022-07-26 11:02
I needed to add this to connection string, but that is another issue: TrustServerCertificate=yes

**Comment by TimelordUK** [comment] 2022-08-16 09:33
Thanks for feedback. I’m closing this issue.

**Closed by TimelordUK** 2022-08-16 09:33 UTC

**Comment by hdoan741** [comment] 2023-12-02 16:20
For anyone who run into this issue again. I've narrowed down the problem to issue with libssl.so.1.1. The problem is solved when installing & using libssl.so.3.0 with LD_PRELOAD like @TimelordUK suggested above.

This is a reliable guide to install it without using brew:
https://github.com/lencx/ChatGPT/issues/458
