### ISSUE TITLE
"[Microsoft][ODBC Driver 17 for SQL Server]Function sequence error" with BCP insert

### ISSUE THREAD

**Issue by wmakeev** [TimelordUK/node-sqlserver-v8#233] opened 2022-02-12 14:03 UTC
Hello! I try to insert rows to table in BCP mode, and get this error:

```
[Microsoft][ODBC Driver 17 for SQL Server]Function sequence error
```

```ts
function getTestRows(num: number) {
  const rows = []

  for (let i = 0; i < num; i++) {
    rows.push({
      id: i + 1,
      name: `name ${i + 1}`
    })
  }

  return rows
}

async function bcp() {
  const connectionString = getConnectionString()

  const connection = await sql.promises.open(connectionString)

  try {
    const table = await connection.promises.getTable(TABLE_NAME)

    table.setUseBcp(true)

    const rows = getTestRows(ROWS_NUM)

    await table.promises.insert(rows)
  } finally {
    await connection.promises.close()
  }
}

bcp()
```

If I not using `table.setUseBcp(true)`, then all works fine.

**My setup:**

- MacOS 11.6.3 (Big Sur)
- Node.js v14.18.0
- Driver microsoft/mssql-release/msodbcsql17 v17.8.1.1
- msnodesqlv8@2.4.5
- Azure SQL (pricing tier - Basic)
- Connection options
    ```
    Driver={ODBC Driver 17 for SQL Server}
    Server=tcp:${MSSQL_HOST},${MSSQL_PORT}
    Database=${MSSQL_DATABASE}
    Uid=${MSSQL_USERNAME}
    Pwd=${MSSQL_PASSWORD}
    Encrypt=yes
    TrustServerCertificate=no
    Connection Timeout=${MSSQL_TIMEOUT}
    ```

**Comment by kenhuman** [comment] 2022-02-15 18:51
I'm seeing a call to sp_describe_first_result_set with the table name while using bcp in a similar situation as above. I believe that the failure happens because the table name is a reserved word and square brackets are not used in the stored procedure call.

**Comment by TimelordUK** [comment] 2022-02-18 10:11
@kenhuman - interesting information thanks

I have run the latest BCP unit test suite on my mac OS build and it works OK

I suggest running one examples to prove that first works it is impossible to diagnose a problem without an exact way to reproduce it, the exact SQL, the exact table, the exact code

**Comment by TimelordUK** [comment] 2022-08-16 09:30
Some Improvements were made since this is raised . I will be closing issue shortly if no further feedback please test latest version.

**Comment by TimelordUK** [comment] 2022-08-23 23:54
Closing

**Closed by TimelordUK** 2022-08-23 23:54 UTC
