### ISSUE TITLE
DeadLock error while saving the data 

### ISSUE THREAD

**Issue by bommojuvishu** [TimelordUK/node-sqlserver-v8#148] opened 2020-03-24 08:22 UTC
### Actual behaviour:

Getting this issue in prod environment where around 30 users are working and trying to update  json data in a table.
The table has a page lock and column where we store complete json.
Somehow it doesn’t release transaction and gives the deadlock issue when another request comes in which updates json in another row.

Code to create connection object  :

`var connection = new sql.ConnectionPool(config);
connection.connect();
app.set('con1', connection);

UpdateJsondetails: function (id, data, success, error) {
        try {
            
   con1.request().input('data1', sql.NVarChar('max'), data).input('id', sql.BigInt,id).execute('update_json').then(function (recordSet) {
                success(recordSet);

            }).catch(function (err) {

                console.log(err);

            });
        } catch (e) {
            logger.error(e.message);
            error(e);
        }
    },
`
SP is

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER     PROCEDURE   [dbo].[update_json]
       -- Add the parameters for the stored procedure here
       @data1 AS nvarchar(max),
          @id  AS bigint
      
AS
BEGIN       
       SET NOCOUNT ON;
         update dataTable set data1=@data1, updated_on= GETDATE() where id=@id 

we are getting the error in the logs as:
originalError: { Error: [Microsoft][SQL Server Native Client 11.0][SQL Server]Transaction (Process ID 398) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction. sqlstate: '40001', code: 1205 }, 

### Software versions

  * NodeJS: 8.11.4
  * node-mssql: 4.1.0
  * msnodesqlv8": 0.6.8
  * SQL Server: Microsoft SQL Server 2016(SP2-GDR) (KB4293802) - 13.0.5081.1 (x64)

**Comment by TimelordUK** [comment] 2020-04-01 11:32
hello

apologies for somewhat late response.

are you actually running this driver on version 8 node?  did you compile the driver yourself on this version as I am pretty sure we only ship binaries >= 10 now.  I am not sure what what point we dropped support for version 8 but this was due to changes in the cpp api meaning it was not easy to keep earlier versions supported once on the newer api.

mssql from memory creates a query statement somewhat like below for a stored procedure - this is what is submitted to the server

```sql
declare @___return___ int, @num3 int;exec @___return___ = test_sp_get_int_int @num1=?, @num2=?, @num3=@num3 output;select @___return___ as '___return___', @num3 as num3;
```

one obvious thing to check would be to ensure msnodesqlv8 raises the 'done' event only after the complete compound statement is run i.e. not after the stored proc call.  I think it is this event that would trigger the pool to place connection back in a ready state.  Is the procedure you are calling complex with many statements?

Also although I understand performance would be hit I wonder if it is possible to check behavior with the pool reduced to fewer connections i.e. is this issue related to calling this procedure via pooled connections. 

The javascript basically submits SQL to a cpp driver which does most of the heavy lifting.  The driver is designed to queue each statement and work on them one at a time.   Each query allocates a statement, that statement is used to fetch all rows and then the javascript tells the driver to release the statement and begin on next.   mssql uses the strreaming api so it is entirely event driven to prevent large memory allocation of rowsets etc

It would seem somehow the deadlock occurs (assuming the procedure itself is not at fault) due to one connection not releasing its statement and retaining the lock.   Is it possible sometimes a storedprocedure silently errors rather than executing i.e. are you catching errors raised?

I am sorry currently I do not have enough to definitavely understand what is going on.  Are you able to reproduce this in a QA environment under load, or are you seeing it every now and then only in production.

**Comment by bommojuvishu** [comment] 2020-04-03 06:10
no.of users increases in prod to 30 above the issue comes up.

**Comment by javierjmatilla** [comment] 2020-04-04 19:48
DeadLocks aren't a problem of this driver, are problems from sql server and your stored procedure:
https://www.mssqltips.com/sqlservertip/5100/lesson-on-sql-server-deadlocks-and-how-to-solve/

**Comment by TimelordUK** [comment] 2020-09-05 10:01
im closing this issue - please try latest version in either case as stated above this does not seem a problem with the library rather the usage within your specific environment .

**Closed by TimelordUK** 2020-09-05 10:01 UTC
