### ISSUE TITLE
PRINT 1 + 1 or USE Database Throws Error

### ISSUE THREAD

**Issue by egmen** [TimelordUK/node-sqlserver-v8#35] opened 2017-03-31 13:21 UTC
This code throws error on the last version (0.2.16) of node-sqlserver-v8. In 0.2.15 everything is OK.
const connStr = 'Driver={SQL Server Native Client 11.0};Server=Server;Trusted_Connection=Yes;'
const sql = require('msnodesqlv8')
var co = {
  conn_str : connStr,
  conn_timeout : 2
}
sql.open(co, (err, conn) => {
  if (err) {
    console.log(err)
    return
  }
  conn.query('print \'print error\'; select 1 as cnt', [], (err, res) => {
    if (err) {
      console.log(err)
    } else {
      console.log(res)
    }
  })
})

**Comment by TimelordUK** [comment] 2017-03-31 13:23
OK, thanks for letting me know, I will take a look and report back shortly.

**Comment by TimelordUK** [comment] 2017-04-07 10:50
I think this related to https://github.com/TimelordUK/node-sqlserver-v8/issues/34

basically if you use queryRaw you can see how this code should now behave.  You can expect a callback with err marked and "more" flag set to true (err, res, more) => { } .

it seems like the query call is not behaving the same way so I will need to change it make them consistent.   But this was done to address a problem where the connection could be put in a broken state i.e. the statement not correctly being cleaned up.

I will make a change to query to make it consistent, but the behaviour will no longer be as previous version of the library,

**Comment by ratanaklun** [comment] 2017-04-07 16:08
This also happens for other commands that print out informative messages like `BACKUP DATABASE`.

**Comment by TimelordUK** [comment] 2017-04-09 20:49
OK, so far I have a new method on the connection which switches dispatch on and off of these non critical events,

so in following example with flag "true"

```typescript
class PrintSelect implements SimpleTest {

    public run(conn_str:string, argv :any): void {
        let delay : number = argv.delay || 5000;

        sql.open(conn_str, (err, conn) => {
            if (err) {
                throw err;
            }
            let x = 1;
            if (err) {
                throw err;
            }
            conn.setFilterNonCriticalErrors(true);
            setInterval( () => {
                conn.query(`print 'JS status message ${x}'; SELECT ${x} + ${x} as res;SELECT ${x} * ${x} as res2`,
                    (err, results, more) => {
                        console.log(`[${x}] more = ${more} err ${err} results ${JSON.stringify(results)}`);
                        if (more) return;
                        ++x;
                    })
            }, delay);
        });
    }
}
````
this will be received as 

[1] more = true err null results [{"res":2}]
[1] more = false err null results [{"res2":1}]
[2] more = true err null results [{"res":4}]
[2] more = false err null results [{"res2":4}]
[3] more = true err null results [{"res":6}]
[3] more = false err null results [{"res2":9}]
[4] more = true err null results [{"res":8}]
[4] more = false err null results [{"res2":16}]

with flag false, 

[1] more = true err Error: [Microsoft][SQL Server Native Client 11.0][SQL Server]JS status message 1 results null
[1] more = true err null results []
[1] more = true err null results [{"res":2}]
[1] more = false err null results [{"res2":1}]
[2] more = true err Error: [Microsoft][SQL Server Native Client 11.0][SQL Server]JS status message 2 results null
[2] more = true err null results []
[2] more = true err null results [{"res":4}]
[2] more = false err null results [{"res2":4}]
[3] more = true err Error: [Microsoft][SQL Server Native Client 11.0][SQL Server]JS status message 3 results null
[3] more = true err null results []
[3] more = true err null results [{"res":6}]
[3] more = false err null results [{"res2":9}]

I have not yet checked in this change.

**Comment by TimelordUK** [comment] 2017-04-11 09:33
actually thinking a little on this it may be better to use the existing string or object mechanism i.e. where a timeout is set on a query, we can add something along lines of 

sql.query(
{
   query_timeout : 1,  // optional
   filter_status_msgs: true // or possibly level i.e. anything < x
}

rather than the rather clumsy method as above.

I will also take a look at how to capture multiple errors from multiple raiseerror .....

**Comment by TimelordUK** [comment] 2017-09-25 10:00
you may want to try the latest version on this ... we now channel non crtitcal errors onto a seperate stream, i.e. warnings should not be raised as errors.

**Comment by TimelordUK** [comment] 2017-10-01 16:13
I added a test for this - I think the issue is now resolved and I will close.

```javascript
  test('print raises warning not error', function (testDone) {
    var fns = [
      function (asyncDone) {
        var warnings = []
        var err = new Error('[Microsoft][SQL Server Native Client 11.0][SQL Server]print error')
        err.code = 0
        err.sqlstate = '01000'
        var expectedErrors = [err]
        var expectedResults = [
          {
            cnt: 1
          }
        ]
        var sql = 'print \'print error\'; select 1 as cnt'
        var q = theConnection.query(sql, [], function (err, res, more) {
          assert.ifError(err)
          if (!more) {
            assert(warnings.length === 1)
            assert.deepEqual(warnings, expectedErrors)
            assert.deepEqual(res, expectedResults)
            asyncDone()
          }
        })
        q.on('error', function (err) {
          assert.ifError(err)
        })
        q.on('warning', function (err) {
          warnings.push(err)
        })
      }
    ]

    async.series(fns, function () {
      testDone()
    })
  })
```

**Closed** 2017-10-01 16:14 UTC
